[@ui.bambooSection title='Where should Bamboo look for the CheckStyle style analysis output?' ]
    [@ww.checkbox label='CheckStyle output will be produced' name='custom.checkstyle.exists' toggle='true' description="CheckStyle validates the sources of your project" /]

    [@ui.bambooSection dependsOn='custom.checkstyle.exists' showOn='true']
        [@ww.textfield name='custom.checkstyle.path' label='CheckStyle Output Directory'
         description='This is where Bamboo will look for the XML report output file generated by CheckStyle.' /]
        [@ww.textfield name='custom.checkstyle.site.url' label='Base HTML Site URL'
         description='This is a HTTP URL of the HTML site that contains the checkstyle report. 
         			It\'s work only for maven2 report, maven2 standard layout and with module name equals arctifactId. 
         			(For example if page is http://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle.html, 
         			the base URL is http://maven.apache.org/plugins/maven-checkstyle-plugin/, 
         			but if this plan builds all plugins, the base URL is http://maven.apache.org/plugins/].' /]
         [@ww.textfield name='custom.checkstyle.threshold.error' label='CheckStyle Error Threshold'
         	description='This is the threshold at or beyond which the build will be failed. Leave blank or -1 for no threshold for failure'/]
         [@ww.textfield name='custom.checkstyle.threshold.warning' label='CheckStyle Warning Threshold'
         	description='This is the threshold at or beyond which the build will be failed. Leave blank or -1 for no threshold for failure'/]
    [/@ui.bambooSection]
[/@ui.bambooSection ]